filebeat.inputs:
  - type: log
    paths:
      - /logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "admin"
  password: "Aloha.32bit"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
