package com.example.kafka.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.UpdateTimestamp;

import java.sql.Timestamp;
import java.time.Instant;

/**
 * Entity class representing an exchange rate.
 * <p>
 * This entity is mapped to the "rates" table in the PostgreSQL database.
 * It stores information about the bid and ask values for a currency pair,
 * as well as timestamps for when the rate was updated and when the record
 * was last modified in the database.
 * </p>
 */
@Entity
@Table(name = "rates")
@Getter
@Setter
public class Rate {
    /**
     * Primary key of the rate record.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(nullable = false)
    private String rateName;

    @Column(nullable = false)
    private float bid;

    @Column(nullable = false)
    private float ask;

    /**
     * Timestamp representing when this rate was last updated
     * by the external source.
     * Cannot be null.
     */
    @Column(nullable = false)
    private Instant rateUpdateTime;
    /**
     * Timestamp automatically updated by Hibernate to reflect
     * when the entity was last updated in the database.
     * Cannot be null.
     */
    @UpdateTimestamp
    @Column(nullable = false)
    private Timestamp dbUpdateTime;
}
